version: '3'
services:
    rental:
        build:
            dockerfile: ./docker/app.dockerfile
            context: .
        image: pontalti/rentalbook
        container_name: rental-book
        ports:
          - "8080:8080"
          - "8000:8000"
        networks: 
            - production-network
            
networks: 
    production-network:
        driver: bridge